/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import model.validations.UserDataValidations;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import exceptions.EmptyFieldException;
import exceptions.InvalidEmailException;
import java.awt.Color;
/**
 *
 * @author pablogarrub
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
         jButtonValidar.setEnabled(true);
        jButtonLimpiar.setEnabled(true);
        jButtonCSV.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelErrorName = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jLabelNIF = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPostalCode = new javax.swing.JLabel();
        jTextFieldPostalCode = new javax.swing.JTextField();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabelErrorNIF = new javax.swing.JLabel();
        jLabelErrorEmail = new javax.swing.JLabel();
        jLabelErrorPostalCode = new javax.swing.JLabel();
        jLabelErrorFecha = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        jLabelEdad = new javax.swing.JLabel();
        jButtonCalculaEdad = new javax.swing.JButton();
        jLabelCorrectName = new javax.swing.JLabel();
        jLabelCorrectNIF = new javax.swing.JLabel();
        jLabelCorrectEmail = new javax.swing.JLabel();
        jLabelCorrectFecha = new javax.swing.JLabel();
        jLabelCorrectPostalCode = new javax.swing.JLabel();
        jLabelUsuarioRegistrado = new javax.swing.JLabel();
        jLabelMONLAU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabeltitulo.setText("VALIDADOR DATOS USUARIO");
        jLabeltitulo.setToolTipText("");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setText("Nombre:");

        jLabelErrorName.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorName.setToolTipText("");

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jLabelNIF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNIF.setText("NIF:");

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha de nacimiento:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail.setText("Email:");

        jLabelPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPostalCode.setText("Codigo Postal:");

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelErrorNIF.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorNIF.setToolTipText("");

        jLabelErrorEmail.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorEmail.setToolTipText("");

        jLabelErrorPostalCode.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorPostalCode.setToolTipText("");

        jLabelErrorFecha.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorFecha.setToolTipText("");

        jButtonLimpiar.setText("Clear");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        jButtonCalculaEdad.setText("Calcula tu edad:");
        jButtonCalculaEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculaEdadActionPerformed(evt);
            }
        });

        jLabelCorrectName.setForeground(new java.awt.Color(51, 204, 0));

        jLabelCorrectNIF.setForeground(new java.awt.Color(51, 204, 0));

        jLabelCorrectEmail.setForeground(new java.awt.Color(51, 204, 0));

        jLabelCorrectFecha.setForeground(new java.awt.Color(51, 204, 0));

        jLabelCorrectPostalCode.setForeground(new java.awt.Color(51, 204, 0));

        jLabelUsuarioRegistrado.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabelUsuarioRegistrado.setForeground(new java.awt.Color(0, 204, 0));

        jLabelMONLAU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/MEDIA/monlau.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelNIF))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCorrectNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelCorrectEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonCSV)
                                                .addGap(57, 57, 57)
                                                .addComponent(jButtonLimpiar))))
                                    .addComponent(jLabelCorrectName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelEmail)
                            .addComponent(jButtonValidar))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jLabelErrorNIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFecha)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCalculaEdad)
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelCorrectFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPostalCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCorrectPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelUsuarioRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabelMONLAU)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabelMONLAU))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelUsuarioRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelName)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCorrectName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorNIF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNIF)
                                .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCorrectNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelEmail)
                                .addComponent(jTextFieldEmail))
                            .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCorrectEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonValidar)
                            .addComponent(jButtonCSV)
                            .addComponent(jButtonLimpiar))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFecha)
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelErrorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCorrectFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCalculaEdad)
                            .addComponent(jLabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPostalCode)
                                .addComponent(jTextFieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelErrorPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCorrectPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initConfig(){
       
        jTextFieldName.setText("");
        jTextFieldNIF.setText("");
        jTextFieldEmail.setText("");
        jTextFieldFecha.setText("");
        jTextFieldPostalCode.setText("");
        jLabelErrorName.setText("");
        jLabelCorrectName.setText("");
        jLabelErrorNIF.setText("");
        jLabelCorrectNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelCorrectEmail.setText("");
        jLabelErrorFecha.setText("");
        jLabelCorrectFecha.setText("");
        jLabelErrorPostalCode.setText("");
        jLabelCorrectPostalCode.setText("");
        jLabelEdad.setText("");
    }
    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        boolean todoCorrecto = true; // Establecer la variable como true por defecto

    try {
        String name = jTextFieldName.getText();
        validarCampoVacio(name, "El nombre");

        String NIF = jTextFieldNIF.getText();
        if (UserDataValidations.checkId(1, NIF) == false) {
            throw new EmptyFieldException("NIF incorrecto");
        }

        String email = jTextFieldEmail.getText();
        validarEmail(email);

        String fecha = jTextFieldFecha.getText();
        if (UserDataValidations.checkFormatDate(fecha) == false) {
            throw new EmptyFieldException("Formato de fecha incorrecto");
        }

        String postal = jTextFieldPostalCode.getText();
        if (UserDataValidations.checkPostalCode(postal) == false) {
            throw new EmptyFieldException("Código postal incorrecto");
        }

        // Si todo es correcto, deshabilitar el botón de validar y habilitar el botón de CSV
        jButtonValidar.setEnabled(false);
        jButtonCSV.setEnabled(true);

        // Limpiar los errores y mostrar mensaje de éxito en verde
        limpiarErrores();
        jLabelUsuarioRegistrado.setText("Datos válidos.");
        jLabelUsuarioRegistrado.setForeground(Color.GREEN); // Cambiar color a verde
    } catch (EmptyFieldException | InvalidEmailException e) {
        // Si ocurre una excepción, mostrar el mensaje de error y habilitar los botones de nuevo
        jLabelUsuarioRegistrado.setText(e.getMessage());
        jLabelUsuarioRegistrado.setForeground(Color.RED); // Cambiar color a rojo

        // Reestablecer la variable de todoCorrecto a false para evitar habilitar el CSV
        todoCorrecto = false;
    }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void limpiarErrores() {
        jLabelErrorName.setText("");
        jLabelErrorNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelErrorFecha.setText("");
        jLabelErrorPostalCode.setText("");
    }
    private void validarCampoVacio(String campo, String nombreCampo) throws EmptyFieldException {
        if (campo == null || campo.trim().isEmpty()) {
        throw new EmptyFieldException(nombreCampo + " no puede estar vacío.");
        }
    }
    private void validarEmail(String email) throws InvalidEmailException {
        if (email == null || email.trim().isEmpty() || !email.contains("@")) {
            throw new InvalidEmailException("Correo electrónico inválido.");
        }
    }
    
    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jButtonValidar.setEnabled(true);
        jButtonLimpiar.setEnabled(true);
        jButtonCSV.setEnabled(false);
        jTextFieldName.setText("");
        jTextFieldName.setEditable(true);
        jTextFieldNIF.setText("");
        jTextFieldNIF.setEditable(true);
        jTextFieldEmail.setText("");
        jTextFieldEmail.setEditable(true);
        jTextFieldFecha.setText("");
        jTextFieldFecha.setEditable(true);
        jTextFieldPostalCode.setText("");
        jTextFieldPostalCode.setEditable(true);
        jLabelErrorName.setText("");
        jLabelCorrectName.setText("");
        jLabelErrorNIF.setText("");
        jLabelCorrectNIF.setText("");
        jLabelErrorEmail.setText("");
        jLabelCorrectEmail.setText("");
        jLabelErrorFecha.setText("");
        jLabelCorrectFecha.setText("");
        jLabelErrorPostalCode.setText("");
        jLabelCorrectPostalCode.setText("");
        jLabelEdad.setText("");
        jLabelUsuarioRegistrado.setText("");
        
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add ur handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    
    private void jButtonCalculaEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculaEdadActionPerformed
    String fecha=jTextFieldFecha.getText();
        int edad=UserDataValidations.calculateAge(fecha);
        if (edad==-1) {
            jLabelEdad.setText("ERROR");
        }
        else{
        jLabelEdad.setText("Tienes "+ edad + " anos");
        }
    }//GEN-LAST:event_jButtonCalculaEdadActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        // TODO add your handling code here:
        String linea=jTextFieldName.getText()+";"+jTextFieldNIF.getText()+";"+jTextFieldEmail.getText()+";"+jTextFieldFecha.getText()+";"+jLabelEdad.getText()+";"+jTextFieldPostalCode.getText()+"\n";
            try (FileWriter writer = new FileWriter("user_data_PGR.csv", true)) {
                writer.write(linea);
                jLabelUsuarioRegistrado.setText("Usuario Registrado Correctamente");
                jButtonCSV.setEnabled(false);
            }
            catch (IOException e) {
                jLabelUsuarioRegistrado.setText("Error al registrar usuario.");
                e.printStackTrace();
                }
    }//GEN-LAST:event_jButtonCSVActionPerformed
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    try (FileWriter writer = new FileWriter("user_data_PGR.csv", false)) {
        writer.write("Nombre;NIF;Email;Fecha;Edad;Código Postal\n"); // Cabecera opcional
        System.out.println("Archivo creado o sobrescrito correctamente.");
    } catch (IOException e) {
        System.out.println("Error al crear o sobrescribir el archivo.");
        e.printStackTrace();
    }

    /* Mostrar la ventana */
    java.awt.EventQueue.invokeLater(() -> new JFrameMain().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonCalculaEdad;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabelCorrectEmail;
    private javax.swing.JLabel jLabelCorrectFecha;
    private javax.swing.JLabel jLabelCorrectNIF;
    private javax.swing.JLabel jLabelCorrectName;
    private javax.swing.JLabel jLabelCorrectPostalCode;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorFecha;
    private javax.swing.JLabel jLabelErrorNIF;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorPostalCode;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMONLAU;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPostalCode;
    private javax.swing.JLabel jLabelUsuarioRegistrado;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPostalCode;
    // End of variables declaration//GEN-END:variables
}
